### ISSUE TITLE
when will you release your code?

### ISSUE THREAD

**Issue by danache** [mohomran/neural_body_fitting#1]
@mohomran Hi, I am interested in your work on 3D mesh prediction , when would you like to release your code?

**Comment by mohomran** [comment]
Hi @danache Appreciate the interest! We will release the code before the end of the month.

**Comment by danache** [comment]
Thx for apply!

**Comment by weigq** [comment]
@mohomran 
I`m also waiting for your updates.

**Comment by Em-Lopez** [comment]
The Termite King demands it Homran!

**Comment by ingramator** [comment]
Please release code! Many people are interested in this research

**Comment by weigq** [comment]
@mohomran  
7 days have past.....

**Comment by holaex** [comment]
@mohomran 
Please ! We are looking forward to your codes!

**Comment by Superlee506** [comment]
Please~Next week is coming

**Comment by mohomran** [comment]
The initial release is now online. Updates to follow.
