### ISSUE TITLE
Fixed

### ISSUE THREAD

**Issue by impredicative** [mohomran/neural_body_fitting#5]

**Comment by Em-Lopez** [comment]
Dude, update it yourself

**Comment by impredicative** [comment]
@em-lopez, please do not interfere since you are not a contributor to the repo. Sometimes, just mind your own business.

**Comment by Em-Lopez** [comment]
Dude, mohomran isn't your employee, and it isn't your place to be demanding shit from him. Should be a bit more grateful, since he is offering the code unlike many academic papers, and furthermore seems to be the only contributor.

**Comment by impredicative** [comment]
@em-lopez Are you new to GitHub? I don't think you understand how this works. Issues are written in a declarative style. The repo maintainer can do with them what they see fit. You have misunderstood the attitude aspect. It's just the style in which issues are written across a diverse number of unrelated repos by a lot of users. Stop taking it personally.

As for the emotive aspect of Python 2 now being sad, it's the motivational cherry on top to discourage the use of Python 2 in the future. Cheers.

**Comment by Em-Lopez** [comment]
Actually, yes I am new to Github. But I believe there is a forking feature that allows independents to submit improvements to the project of their choice. And a merge or something like that? Wouldn't it be easier making changes yourself, instead of pushing them on others?

**Comment by impredicative** [comment]
@Em-Lopez GitHub allows for issues so people can make requests and notify of bugs or questions and concerns. The repo maintainer has an option to disable issues for this repo if they so desire.

**Comment by ducha-aiki** [comment]
@impredicative what about people, who religiously don`t like Python 3?)

**Comment by impredicative** [comment]
This repo and issue has attracted trolls. This issue is therefore being closed.
