### ISSUE TITLE
When is the train code released?

### ISSUE THREAD

**Issue by ChenyuGao** [mohomran/neural_body_fitting#7]
Thank you for your exciting work, I am hoping to study your train code.
On the other hand, does the 161th row of write_output.py have a problem? The function 'render_body_impl' does not have the parameter 'path_to_mesh'.

**Comment by Em-Lopez** [comment]
Hehe.

**Comment by GaoChenyuchn** [comment]
> Hehe.

**Comment by ChenyuGao** [comment]
OK, I have known. I use the official code repository of up.
